export const config = {
  JWT_SECRET: `MIIBOQIBAAJActV4kFohiit6lHbkjnv5lBT+um/Syd++kUsX5J/ZxIutK94GBi5l
kTI27SPA9twygkBjBPwibF1QrZ2iT8TZnQIDAQABAkAyj7ueE5Fg/PPkGtVXx06E
3RmrjUEKkfGel6nViGyiFSCsxZi/3JM+ThWqus8UftShpZuIzpYSo91f/lEqeREh
AiEA5TlF6ZI/WjKPLl1riyXI2Q1+lm3PIQQIMwdRRQV+rPMCIQCAP3kwWQ8GlsPJ
rAibUH2oO2QRlygwc6vGGwQsqqLDLwIhAIP2OeJimGgzzSwTChOcWAlk9GhjpSfL
q3C9GLNUm32zAiBaEDlDQsfSkL4eOrowmG4mXs7/q2+F1zWiggaEd7Cl8QIgOzIA
haLkCDFnm1iXcRFCZSAFX3pfjA8Tjp2mZiHsvc4=`,
  // ALL_COMPANY: ['SCAN', 'SEREN', 'IPC', 'SAHP', 'MERQ']
};
