export const GET_PARTS = "GET_PARTS";
export const CREATE_PART = "CREATE_PART";
export const UPDATE_PART = "UPDATE_PART";
export const DELETE_PART = "DELETE_PART";

export const GET_NG_CAUSES = "GET_NG_CAUSES";
export const CREATE_NG_CAUSE = "CREATE_NG_CAUSE";
export const UPDATE_NG_CAUSE = "UPDATE_NG_CAUSE";
export const DELETE_NG_CAUSE = "DELETE_NG_CAUSE";

export const CREATE_DEFECT = "CREATE_DEFECT";
export const UPDATE_DEFECT = "UPDATE_DEFECT";
export const DELETE_DEFECT = "DELETE_DEFECT";
export const GET_RAW_DEFECTS = "GET_DEFECTS";

export const GET_DEFECT_SUMMARIES_BY_DATE = "GET_DEFECT_SUMMARIES_BY_DATE";
export const GET_GRAPH_SUMMARIES = "GET_GRAPH_SUMMARIES";
export const GET_TOP_DEFECTS = "GET_TOP_DEFECTS";

export const CREATE_PRODUCTIVITY = "CREATE_PRODUCTIVITY";
export const UPDATE_PRODUCTIVITY = "UPDATE_PRODUCTIVITY";
export const DELETE_PRODUCTIVITY = "DELETE_PRODUCTIVITY";
export const GET_RAW_PRODUCTIVITYS = "GET_RAW_PRODUCTIVITYS";
export const GET_PRODUCTIVITY_SUMMARIES_BY_DATE = "GET_PRODUCTIVITY_SUMMARIES_BY_DATE";

// Productivity

//Machine
export const GET_MACHINES = "GET_MACHINES";
export const CREATE_MACHINE = "CREATE_MACHINE";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
export const DELETE_MACHINE = "DELETE_MACHINE";

//Account
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
